spring:
  application:
    name: transactionservice
  datasource:
    url: jdbc:mysql://localhost:3306/transactiondb
    username: transactionuser
    password: transactionpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8083