spring:
  application:
    name: investmentservice
  datasource:
    url: jdbc:mysql://localhost:3306/investmentdb # çok önemli
    username: investmentuser
    password: investmentpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa: # A Java class annotated with @Entity represents a table in a database.
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate: # çok önemli
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8081

feign:
  hystrix:
    enabled: true
